<?php

namespace Ben\AssociationBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * eventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eventRepository extends EntityRepository
{
    public function search($searchParam) {
        extract($searchParam);    
        $qb = $this->createQueryBuilder('e')
                ->leftJoin('e.groups', 'g')
                ->addSelect('g')
                ->andWhere('e.name like :keyword or e.description like :keyword or e.type like :keyword')
                ->setParameter('keyword', '%'.$keyword.'%');
        if(!empty($group))
            $qb->andWhere('g.id = :group')->setParameter('group', $group);
        if(!empty($date)){
            $date = explode("-",$date);
            $qb->andWhere('e.date_from between :d1 and :d2')
            ->setParameter('d1', $date[0])
            ->setParameter('d2', $date[1]);
        }
        $qb->setFirstResult(($page - 1) * $perPage)
        ->setMaxResults($perPage);
        
       return new Paginator($qb->getQuery());
    }
    
    public function counter() {
        $query = $this->_em->createQuery('SELECT count(e) FROM ben\AssociationBundle\Entity\event e');
        return $query->getOneOrNullResult();
    }
}
