<?php

namespace Ben\AssociationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldsRepository extends EntityRepository
{
    public function updateFields($config)
    {
        extract($config);
        $qB = $this->getEntityManager()->createQueryBuilder()
            ->update('BenAssociationBundle:fields', 'f')
            ->set('f.nicename', ':nicename') ->setParameter('nicename', $nicename)
            ->set('f.visible', ':visible')->setParameter('visible', isset($visible))
            ->where('f.id = :id')->setParameter('id', $id);
         
        return $qB->getQuery()->execute();
    }
}
