<?php

namespace Ben\AssociationBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
    public function findSome($nombreParPage, $page, $keyword, $group, $dateFrom, $dateTo) {       
       $qb = $this->createQueryBuilder('r')
                ->leftJoin('r.room', 'room')
                ->addSelect('room')
                ->leftJoin('room.hotel', 'hotel')
                ->addSelect('hotel')
                ->leftJoin('r.user', 'u')
                ->addSelect('u')
                ->leftJoin('u.profile', 'p')
                ->addSelect('p')
                ->andWhere('u.username like :keyword or p.first_name like :keyword or p.family_name like :keyword or hotel.name like :keyword ')
                ->setParameter('keyword', '%'.$keyword.'%')
                ->orderBy('r.date_from', 'DESC');
        if($group){
        	$qb->leftJoin('u.groups', 'g')
            ->andWhere('g.id = :group')->setParameter('group', $group);
        }
        if($dateFrom)
            $qb->andWhere('r.date_from = :dateFrom')->setParameter('dateFrom', $dateFrom);
        if($dateTo)
            $qb->andWhere('r.date_to = :dateTo')->setParameter('dateTo', $dateTo);
        $qb->setFirstResult(($page - 1) * $nombreParPage)
        ->setMaxResults($nombreParPage);
        
       return new Paginator($qb->getQuery());
    }
    
    public function counter() {
        $query = $this->_em->createQuery('SELECT count(r) FROM ben\AssociationBundle\Entity\Reservation r');
        return $query->getOneOrNullResult();
    }	
	
}
