<?php

namespace Ben\AssociationBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RoomsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomsRepository extends EntityRepository
{
	public function getFloors()
	{
		 $qb = $this->createQueryBuilder('r')
		 		->select('distinct(r.floor)')
		 		->getQuery();
		 
		 return $qb->getArrayResult();
	}
    public function search($nombreParPage, $page, $keyword, $searchEntity) {      
       $qb = $this->createQueryBuilder('r')
                ->leftJoin('r.hotel', 'h')
                ->addSelect('h')
                ->andWhere('h.name like :keyword or h.city like :keyword or h.description like :keyword')
                ->setParameter('keyword', '%'.$keyword.'%');

        if($searchEntity){
          extract($searchEntity); 
          if(!empty($name)){
          	$qb->andWhere('r.number = :name')
                 ->setParameter('name', $name);
          }
          if(!empty($block)){
            $qb->andWhere('h.name like :block')
                 ->setParameter('block', '%'.$block.'%');
          }
          if(!empty($floor)){
          	$qb->andWhere('r.floor = :floor')
                 ->setParameter('floor', $floor);
          }
          if(!empty($max)){
            $qb->andWhere('r.max = :max')
                 ->setParameter('max', $max);
          }
          if(!empty($gender)){
            $qb->andWhere('r.type = :type')
                 ->setParameter('type', $gender);
          }

          if(!empty($status)){
              if($status === 'free') $qb->andWhere('r.free > 0');
              elseif($status === 'notfree') $qb->andWhere('r.free = 0');
          }
        }
                
        $qb->setFirstResult(($page - 1) * $nombreParPage)
        ->setMaxResults($nombreParPage);
        
       return new Paginator($qb->getQuery());
    }

    public function counter() {
        $query = $this->_em->createQuery('SELECT count(r) FROM ben\AssociationBundle\Entity\Rooms r');
        return $query->getOneOrNullResult();
    } 
	
}
